blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature request
    url: https://github.com/davidjerleke/embla-carousel/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
  - name: â“ Ask for help
    url: https://github.com/davidjerleke/embla-carousel/discussions/new?category=help
    about: Ask questions about how to achieve something
  - name: âœ¨ Show something
    url: https://github.com/davidjerleke/embla-carousel/discussions/new?category=show-and-tell
    about: Share something you've built with Embla Carousel
  - name: ğŸ’¬ Discuss
    url: https://github.com/davidjerleke/embla-carousel/discussions/new?category=general
    about: Start conversation or discussion about something
